src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="integer")
     */
    private $Qte;

    /**
     * @ORM\Column(type="text")
     */
    private $Adresse_livraison;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class)
     */
    private $product;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQte(): ?int
    {
        return $this->Qte;
    }

    public function setQte(int $Qte): self
    {
        $this->Qte = $Qte;

        return $this;
    }

    public function getAdresseLivraison(): ?string
    {
        return $this->Adresse_livraison;
    }

    public function setAdresseLivraison(string $Adresse_livraison): self
    {
        $this->Adresse_livraison = $Adresse_livraison;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $designation;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $label;

    /**
     * @ORM\Column(type="text", length=100, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_creation;

    /**
     * @ORM\Column(type="string")
     */
    private $image_of_product;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getDesignation()
    {
        return $this->designation;
    }

    /**
     * @param mixed $designation
     */
    public function setDesignation($designation): void
    {
        $this->designation = $designation;
    }

    /**
     * @return mixed
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * @param mixed $label
     */
    public function setLabel($label): void
    {
        $this->label = $label;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description): void
    {
        $this->description = $description;
    }

    /**
     * @return mixed
     */
    public function getDateCreation()
    {
        return $this->date_creation;
    }

    /**
     * @param mixed $date_creation
     */
    public function setDateCreation($date_creation): void
    {
        $this->date_creation = $date_creation;
    }

    /**
     * @return mixed
     */
    public function getImageOfProduct()
    {
        return $this->image_of_product;
    }

    /**
     * @param mixed $image_of_product
     */
    public function setImageOfProduct($image_of_product): void
    {
        $this->image_of_product = $image_of_product;
    }

}

src/Form/CommandeType.php
<?php

namespace App\Form;

use App\Entity\Commande;
use App\Entity\Product;
use App\ProductType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Qte')
            ->add('Adresse_livraison')
           // ->add('id_product',ProductType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
        ]);
    }
}

src/Controller/CommandesController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Entity\Product;
use App\Form\CommandeType;
use App\Repository\CommandeRepository;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class CommandesController extends AbstractController
{
    /**
     * @Route("/commandes", name="commandes")
     */
    public function index(EntityManagerInterface $em,CommandeRepository $commandeRepository)
    {
        $commandes =  $commandeRepository->find(4);
        $p = $commandes->getProduct();
        return $this->render('commandes/index.html.twig', [
            'controller_name' => 'CommandesController',
            'commande'=>$commandes
        ]);
    }
    /**
     * @Route ("/newOrder", name="commandes_new_order")
     */
    public function newOrder(ProductRepository $productRepository,Request $request,EntityManagerInterface $em){
        $cmd = new Commande();
        $cmd->setAdresseLivraison('Adresse de test');
        $cmd->setQte(2);
        //$p = new Product();
        $p = $productRepository->find(1);
        //$cmd->addIdProduct($p);
        $form = $this->createForm(CommandeType::class,$cmd);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $cmd->setProduct($p);
            $em->persist($cmd);
            $em->flush();
            return $this->redirectToRoute("commandes");

        }
        return $this->render('commandes/new.html.twig',array('form'=>$form->createView(),'controller_name' => 'CommandesController'));
    }
}

templates/commandes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CommandesController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/21802/Desktop/workspace/Eboutique/src/Controller/CommandesController.php'|file_link(0) }}">src/Controller/CommandesController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/21802/Desktop/workspace/Eboutique/templates/commandes/index.html.twig'|file_link(0) }}">templates/commandes/index.html.twig</a></code></li>
    </ul>
</div>
    <div>
        {{ commande.qte }}
        {{ commande.AdresseLivraison }}
       <img src="{{ commande.product.imageOfProduct }}"/>
    </div>
{% endblock %}

templates/commandes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CommandesController!{% endblock %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/21802/Desktop/workspace/Eboutique/src/Controller/CommandesController.php'|file_link(0) }}">src/Controller/CommandesController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/21802/Desktop/workspace/Eboutique/templates/commandes/index.html.twig'|file_link(0) }}">templates/commandes/index.html.twig</a></code></li>
    </ul>
</div>
    <div>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <input type="submit" value="Passer la commande">
        {{ form_end(form) }}
    </div>
{% endblock %}